trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  apiProject: 'src/Presentation/Appointments.API/Appointments.API.csproj'
  outputDir: '$(build.artifactStagingDirectory)/api'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration) --output $(outputDir)'
    zipAfterPublish: true

- script: ls -la $(outputDir)
  displayName: 'Listar archivos publicados del API'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'api'
    downloadPath: '$(System.DefaultWorkingDirectory)/api'

- task: AzureRmWebAppDeployment@5
  displayName: "despliegue API"
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Suscripción de Azure 1(5dca32b6-0caf-4e1b-ade7-51b7b52dd1fa)'
    appType: 'webAppLinux'
    WebAppName: 'AppointmentsAPI'
    packageForLinux: '$(System.DefaultWorkingDirectory)/api/Appointments.API.zip'
    DeploymentTypeLinux: 'oneDeploy'