trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  apiProject: 'src/Presentation/Appointments.API/Appointments.API.csproj'
  outputDir: '$(build.artifactStagingDirectory)/api'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration) --output $(outputDir)'
    zipAfterPublish: true

- script: ls -la $(outputDir)
  displayName: 'Listar archivos publicados del API'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(outputDir)'
    artifactName: 'api'
    publishLocation: 'Container'